package com.kmjd.jsylc.zxh.database.dbbean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LOGIN_INFORMATION".
 */
@Entity
public class LoginInformation {

    @Id
    private Long id;
    private String accountId;
    private String password;

    @Generated(hash = 917130239)
    public LoginInformation() {
    }

    public LoginInformation(Long id) {
        this.id = id;
    }
    public LoginInformation(String accountId, String password) {
        this.accountId = accountId;
        this.password = password;
    }
    @Generated(hash = 788468532)
    public LoginInformation(Long id, String accountId, String password) {
        this.id = id;
        this.accountId = accountId;
        this.password = password;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
