package com.kmjd.jsylc.zxh.database.dbbean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PUBLIC_MESSAGE".
 */
@Entity
public class PublicMessage {

    @Id
    private Long id;
    private String publicMessageId;

    @Generated(hash = 173600014)
    public PublicMessage() {
    }

    public PublicMessage(Long id) {
        this.id = id;
    }

    public PublicMessage( String publicMessageId) {
        this.publicMessageId = publicMessageId;
    }

    @Generated(hash = 2050110695)
    public PublicMessage(Long id, String publicMessageId) {
        this.id = id;
        this.publicMessageId = publicMessageId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPublicMessageId() {
        return publicMessageId;
    }

    public void setPublicMessageId(String publicMessageId) {
        this.publicMessageId = publicMessageId;
    }

}
