package com.md.jsyxzs_cn.zym_xs.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NET_SPEED".
 */
public class NetSpeedInfo {

    private Long id;
    private String net_name;
    private String net_speed_info;
    private String old_net_speed_info;
    private String net_address;
    private String net_website_name;
    private Boolean net_is_testing;
    private int status;
    private int websitIsVaild;//网络站点是否有效，默认是0，如果有效保存为1，如果无效保存为2

    public NetSpeedInfo() {
    }

    public NetSpeedInfo(Long id) {
        this.id = id;
    }

    public NetSpeedInfo(String net_speed_info, String net_address, Boolean net_is_testing, String net_website_name) {
        this.net_speed_info = net_speed_info;
        this.net_address = net_address;
        this.net_is_testing = net_is_testing;
        this.net_website_name = net_website_name;
        this.old_net_speed_info = "0.0";
    }

    public NetSpeedInfo(String net_name, String net_speed_info, String net_address, String net_website_name, Boolean net_is_testing) {
        this.net_name = net_name;
        this.net_speed_info = net_speed_info;
        this.net_address = net_address;
        this.net_website_name = net_website_name;
        this.net_is_testing = net_is_testing;
    }

    public NetSpeedInfo(Long id, String net_name, String net_speed_info, String net_address, String net_website_name, Boolean net_is_testing) {
        this.id = id;
        this.net_name = net_name;
        this.net_speed_info = net_speed_info;
        this.net_address = net_address;
        this.net_website_name = net_website_name;
        this.net_is_testing = net_is_testing;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNet_name() {
        return net_name;
    }

    public void setNet_name(String net_name) {
        this.net_name = net_name;
    }

    public String getNet_speed_info() {
        return net_speed_info;
    }

    public void setNet_speed_info(String net_speed_info) {
        this.net_speed_info = net_speed_info;
    }

    public String getOld_net_speed_info() {
        return old_net_speed_info;
    }

    public void setOld_net_speed_info(String old_net_speed_info) {
        this.old_net_speed_info = old_net_speed_info;
    }

    public String getNet_address() {
        return net_address;
    }

    public void setNet_address(String net_address) {
        this.net_address = net_address;
    }

    public String getNet_website_name() {
        return net_website_name;
    }

    public void setNet_website_name(String net_website_name) {
        this.net_website_name = net_website_name;
    }

    public Boolean getNet_is_testing() {
        return net_is_testing;
    }

    public void setNet_is_testing(Boolean net_is_testing) {
        this.net_is_testing = net_is_testing;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getWebsitIsVaild() {
        return websitIsVaild;
    }

    public void setWebsitIsVaild(int websitIsVaild) {
        this.websitIsVaild = websitIsVaild;
    }

}
